### ISSUE TITLE
Contributing to the DevTools

### ISSUE THREAD

**Issue by captainbrosset** [programmin1/DevTools-Tweaks#2]
Hey, awesome addon!

We've built-in some of the features you introduced in the devtools by now.
It'd be awesome if you could contribute to the devtools directly. Since we don't have a proper extension API for now (although we're working on it), maintaining an addon it's going to prove pretty challenging on the long run.

**Comment by programmin1** [comment]
I'm glad to see Firefox is moving to a more tweak-able Firefox-devtools.
https://hacks.mozilla.org/2016/02/introducing-devtools-reload/

If they focus on stability and squashing the rest of the annoying inspector/debugger core bugs, we should see more and more specific addons for specific use cases (like Devtool-tweaks!)
