### ISSUE TITLE
Compatibility support for Fx42

### ISSUE THREAD

**Issue by ochameau** [programmin1/DevTools-Tweaks#6]
You are importing a file that is about to be removed from Firefox: LayoutHelpers.jsm.
At least from inspectorTweaks.js.

This file is still going to be around, but in another shape. Here is how to import it:
```
  let {devtools} = Cu.import("resource://gre/modules/devtools/Loader.jsm", {});
  let LayoutHelpers = devtools.require("devtools/toolkit/LayoutHelpers");
```
Note that this is not backward compatible and you would need to support both ways for importing this helper...

**Comment by ochameau** [comment]
Here is the related bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1182194

**Comment by programmin1** [comment]
The latest version should have had all these paths changed. Working for me in version 44.
