### ISSUE TITLE
Compare nodes not working

### ISSUE THREAD

**Issue by nt1m** [programmin1/DevTools-Tweaks#7]
I use Nightly 49.
clicking Set Node A then doing click Set Node B and compare

That doesn't seem to work.

**Comment by programmin1** [comment]
Sorry for the delay. The Select second node has to be in a tab within the same window. Seems to be working in my Firefox 48.

Seems the menu items are not showing up on my Firefox 50, which I'll have to look into later.

**Comment by programmin1** [comment]
Correction - I noticed this the other day, and it has to be used with devtools _within_ the window _not detached, but in the same window_.

**Comment by programmin1** [comment]
This should be fixed - current Git version should let you compare any nodes in any window, and it now works with Firefox 50.

**Comment by mikhoul** [comment]
You should put a beta version of the XPI file here :octocat:   I would update right now ! :smiley_cat:

**Comment by programmin1** [comment]
I just uploaded it to AMO:

https://addons.mozilla.org/en-US/firefox/addon/devtools-tweaks/versions/?page=1#version-0.6

**Comment by mikhoul** [comment]
:+1:
